### ISSUE TITLE
packages=['nvsa'], install_requires=['pytorch'], zip_safe=False)

### ISSUE THREAD

**Issue by dbl001** [IBM/neuro-vsa#2]
Do you mean 'torch' instead of 'pytorch' here?

```
pip install git+https://github.com/IBM/neuro-vector-symbolic-architectures.git --verbose
...
 Building wheel for nvsa (setup.py) ... done
  Created wheel for nvsa: filename=nvsa-0.1-py3-none-any.whl size=5343 sha256=07f81a77c7d3cc9490f08a9bdf8333fd1a2cc4f417d62ecf6b7b5a059bc16440
  Stored in directory: /private/var/folders/3n/56fpv14n4wj0c1l1sb106pzw0000gn/T/pip-ephem-wheel-cache-1vrv64ye/wheels/bc/6b/9f/3f265f7fb272601649346d156fafbf2e2a5cfc5807b2071fa3
  Running command python setup.py bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/var/folders/3n/56fpv14n4wj0c1l1sb106pzw0000gn/T/pip-install-ja3flql0/pytorch_80f41182590244bcba54bcf13e076f65/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/davidlaxer/tensorflow/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/var/folders/3n/56fpv14n4wj0c1l1sb106pzw0000gn/T/pip-install-ja3flql0/pytorch_80f41182590244bcba54bcf13e076f65/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/var/folders/3n/56fpv14n4wj0c1l1sb106pzw0000gn/T/pip-wheel-ug119e0h
  cwd: /private/var/folders/3n/56fpv14n4wj0c1l1sb106pzw0000gn/T/pip-install-ja3flql0/pytorch_80f41182590244bcba54bcf13e076f65/
  Building wheel for pytorch (setup.py) ... error
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
  Running command python setup.py clean
  running clean
  'build/lib' does not exist -- can't clean it
  'build/bdist.macosx-10.9-x86_64' does not exist -- can't clean it
  'build/scripts-3.8' does not exist -- can't clean it
Successfully built nvsa
Failed to build pytorch
ERROR: Could not build wheels for pytorch, which is required to install pyproject.toml-based projects

```

**Comment by assissanliu** [comment]
把setup.py里面的pytorch改为torch
